### ISSUE TITLE
Remove NHS 

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#126]
Remove NHS Options? @daniel-sudz

**Comment by theTisch21** [comment]
I'm currently in NHS, and my officer has told me I don't have to fill stuff out here. I wouldn't mind if this feature is removed from the tracker.

**Comment by davidvel25** [comment]
I believe the NHS tracker should remain because unlike other trackers such as NHS-specific community service submission pages and EHS Interact Club community service submission pages, the student is not able to see how many hours they have submitted once they have clicked "Submit". This tracker that was made is a great place to store ALL the hours for NHS, Key Club, and other clubs etc. So even though this tracker is not used by NHS, I can clearly see ALL the hours I have submitted because this tracker allows the user to view and edit all their hours unlike Microsoft Forms. It also doesn't hurt to keep it, so I say we should keep the NHS button.

**Comment by Zjjc123** [comment]
@davidvel25 so keep it as a way to track but not for official use?

**Comment by davidvel25** [comment]
@Zjjc123 Yeah exactly! I think only Key Club uses this tracker, so I think that since its UI is so intuitive to use, it can also be used to track for other clubs even though they don't use this tracker as the primary method.
